rzd_instruction_book/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.ShowTopicTests.as_view(), name='test_topic'),
    path('test/<int:topic_id>/', views.ChoiceTopic.as_view(), name='test'),
    # path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

rzd_instruction_book/rzd_instruction_book/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from rzd_instruction_book import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
    path('', include('instruction.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rzd_instruction_book/polls/models.py
from django.db import models
from django.contrib.auth.models import User



class Question(models.Model):
    text = models.CharField(max_length=500, verbose_name='Текст')
    num_right = models.IntegerField(verbose_name='Количество правильных ответов')

    def __str__(self):
        return self.text

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=500, verbose_name='Ответ')
    right = models.BooleanField(default=False, verbose_name='Правильный')

    def __str__(self):
        return self.text


class Test(models.Model):
    title = models.CharField(max_length=300, verbose_name='Тема')
    questions = models.ManyToManyField(Question)

    def __str__(self):
        return self.title

class Topic(models.Model):
    title = models.CharField(max_length=250, verbose_name='Название')
    theory = models.CharField(max_length=1000, verbose_name='Теория')
    tests_s = models.ManyToManyField(Test)

    def __str__(self):
        return self.title

class Test_Result(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    result = models.CharField(verbose_name='Результат', max_length=300)

    def __str__(self):
        return self.result

rzd_instruction_book/polls/forms.py
from django import forms
from .models import *

class TestForm(forms.ModelForm):
    def __int__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        q = Question.objects.get(id=1)
        self.fields['question'].emty_label = "Вопрос"

    class Meta:
        model = Answer
        fields = ['question', 'text', 'right']

rzd_instruction_book/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect, request
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView

from .utils import *
from . models import Question, Answer, Test
from . forms import *


class ChoiceTopic(ListView):
    model = Test
    template_name = 'polls/test.html'
    context_object_name = 'test_choice'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['test_choice'] = get_object_or_404(Test, id=self.kwargs['topic_id'])
        context['question_list'] = get_object_or_404(Test, id=self.kwargs['topic_id']).questions.all()
        return context

# def choice_topic(request, topic_id):
#     test_choice = get_object_or_404(Test, pk=topic_id)
#     print(test_choice)
#     question_list = test_choice.questions.all()
#     print(question_list)
#     data = {
#         'question_list': question_list,
#         'test_choice': test_choice,
#
#     }
#
#     return render(request, 'polls/test.html', context=data)


class ShowTopicTests(ListView, DataMixin):
    model = Test
    context_object_name = 'topics_test'
    template_name = 'base.html'
    # extra_context = {'menu': menu}

    def get_context_data(self, *, objects_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context() ## вызываем метод у миксина и присваиваем переменной
        context.update(c_def) ## обновляем context из mixin
        # context['menu'] = menu
        return context


#
def vote(request, question_id):
    # all_answer = question.answer_set.all()
    # print(all_answer)
    question = get_object_or_404(Question, pk=question_id)
    print(question)

    # print(selected_choice)
    right_answer = question.answer_set.get(right=True)
    # print(right_answer)
    try:
        selected_choice = question.answer_set.get(pk=request.POST['choice'])
        print(request.POST['choice'])
    except (KeyError, Answer.DoesNotExist):
        return HttpResponse('Выбирете ответ')
    else:
        if selected_choice.right is True:
            return render(request, 'polls/result_tests.html', {'selected_choice': selected_choice, 'question': question})
        else:
            return render(request, 'polls/result_tests.html', {'right_answer': right_answer, 'question': question})


# class Vote(ListView):
#     model = Question
#     template_name = 'polls/result_tests.html'
#
#     context_object_name = 'question'
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['question'] = get_object_or_404(Question, pk = self.kwargs['question_id'])
#         context['selected_choice'] = get_object_or_404(
#             Question, pk = self.kwargs['question_id']).answer_set.get(pk=request.POST['choice'])
#         print(context)
#         return context

rzd_instruction_book/polls/templates/polls/choice_tests.html
<!--{% extends 'base.html' %}-->



<!--{% block choice_test %}-->
<!--{% for topic in topics_test %}-->
<!--<li><a href="{% url 'polls:test' topic.id %}">{{topic}}</a></li>-->
<!--{% endfor %}-->
<!--{% endblock %}-->

rzd_instruction_book/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>



</form>


</body>
</html>

rzd_instruction_book/polls/templates/polls/result_tests.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h2>Вопрос: {{ question }}</h2>

{% if selected_choice %}
<h1>Ваш ответ, верный:) {{ selected_choice }} </h1>
{% else %}
<h1>Ваш ответ, не верный! :(  Правильный ответ: {{ right_answer }}</h1>
{% endif %}




<button ><a href="javascript:history.back()" title="Вернуться к вопросам" > Вернуться к вопросам </a></button>

</body>
</html>

rzd_instruction_book/polls/templates/polls/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ test_choice }}</title>
</head>
<body>
{% block test %}
<div class="test">
<h1 align="center">{{test_choice}}</h1>
<button ><a href="/" title="Вернуться к вопросам" > Вернуться на главную </a></button>

{% for question in  question_list%}
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
    <fieldset>
        <legend><h1>{{ question }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>
        {% endif %}
        {% for choice in question.answer_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Ответить">
</form>
{% endfor %}
</div>
</body>
</html>
{% endblock %}

rzd_instruction_book/polls/templates/polls/test_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Тесты</h1>

<form action="{% url 'tests' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Ответить</button>
</form>



</body>
</html>